apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcg-catalogapi
  namespace: fcg-prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /catalog(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalogapi
                port:
                  number: 80
