// <auto-generated />
using System;
using FCG.Catalog.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCG.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116194450_primary-migration")]
    partial class primarymigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_JOGO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2000)")
                        .HasColumnName("DSC_DESCRICAO");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VLR_DESCONTO");

                    b.Property<int>("GenderId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_GENERO");

                    b.Property<int>("PlataformId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_PLATAFORMA");

                    b.Property<decimal?>("Price")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VLR_PRECO");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("DSC_TITULO");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("PlataformId");

                    b.ToTable("TB_JOGO", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_GENERO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("DSC_TITULO");

                    b.HasKey("Id");

                    b.ToTable("TB_GENERO", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Plataform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_PLATAFORMA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("DSC_TITULO");

                    b.HasKey("Id");

                    b.ToTable("TB_PLATAFORMA", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_USUARIO_JOGO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<int>("GameId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_JOGO");

                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("TB_USUARIO_JOGO", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Game", b =>
                {
                    b.HasOne("FCG.Catalog.Domain.Entities.Gender", "Gender")
                        .WithMany("Games")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCG.Catalog.Domain.Entities.Plataform", "Plataform")
                        .WithMany("Games")
                        .HasForeignKey("PlataformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Plataform");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.UserGame", b =>
                {
                    b.HasOne("FCG.Catalog.Domain.Entities.Game", "Game")
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Game", b =>
                {
                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Gender", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Entities.Plataform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
